Repository TeamMody/mody-server, pull requests merged in 2025-01, with the labels that each got.

#12 🔧 [CHORE] CICD 구축
  .github/workflows/mody-dev.yml
  .github/workflows/mody-prod.yml
  Dockerfile
  appspec.yml
  build.gradle
  docker-compose-dev.yml
  docker-compose-prod.yml
  scripts/stop.sh
  src/main/java/com/example/mody/ModyApplication.java
  src/main/resources/application-dev.yml
Labels: 🌏Deploy

#15 🔧 [CHORE] #14 - spring security, oauth 의존성 추가
  build.gradle
Labels: 📃 Docs

#20 ✨ [FEATURE] #13 - 게시글 등록 API 구현
  build.gradle
  src/main/java/com/example/mody/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mody/domain/auth/security/CustomUserDetails.java
  src/main/java/com/example/mody/domain/backupimage/dto/request/BackupFileRequest.java
  src/main/java/com/example/mody/domain/backupimage/entity/BackupFile.java
  src/main/java/com/example/mody/domain/backupimage/repository/BackupFileRepository.java
  src/main/java/com/example/mody/domain/backupimage/service/BackupFileService.java
  src/main/java/com/example/mody/domain/bodytype/entity/BodyType.java
  src/main/java/com/example/mody/domain/bodytype/entity/MemberBodyType.java
  src/main/java/com/example/mody/domain/bodytype/repository/BodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/BodyTypeService.java
  src/main/java/com/example/mody/domain/exception/BodyTypeException.java
  src/main/java/com/example/mody/domain/exception/PostException.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/member/service/MemberQueryService.java
  src/main/java/com/example/mody/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/mody/domain/post/constant/PostConstant.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/entity/PostImage.java
  src/main/java/com/example/mody/domain/post/repository/PostRepository.java
  src/main/java/com/example/mody/domain/post/service/PostCommandService.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/global/common/base/BaseResponse.java
  src/main/java/com/example/mody/global/common/exception/code/status/BodyTypeErrorStatus.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: ✨ Feature, 🔨 Refactor

#24 🔨 [REFACTOR] #23 - BodyType 엔티티 수정
  src/main/java/com/example/mody/domain/bodytype/entity/MemberBodyType.java
  src/main/java/com/example/mody/domain/bodytype/entity/mapping/MemberBodyType.java
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/BodyTypeService.java
Labels: 🔨 Refactor

#27 ♻️ @AuthenticationPrincipal을 사용하도록 Refactor
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/auth/controller/OAuth2Controller.java
  src/main/java/com/example/mody/domain/auth/dto/request/MemberRegistrationRequest.java
  src/main/java/com/example/mody/domain/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/mody/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mody/domain/auth/security/CustomUserDetails.java
  src/main/java/com/example/mody/domain/auth/security/CustomUserDetailsService.java
  src/main/java/com/example/mody/domain/auth/security/OAuth2UserService.java
  src/main/java/com/example/mody/domain/member/converter/MemberConverter.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/member/enums/LoginType.java
  src/main/java/com/example/mody/domain/member/repository/MemberRepository.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandService.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/code/status/MemberErrorStatus.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#28 ✨ [FEATURE] #16 - 체형 분석 결과 구현
  src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeController.java
  src/main/java/com/example/mody/domain/bodytype/entity/Answer.java
  src/main/java/com/example/mody/domain/bodytype/entity/BodyType.java
  src/main/java/com/example/mody/domain/bodytype/entity/Question.java
  src/main/java/com/example/mody/domain/bodytype/entity/mapping/MemberAnswer.java
  src/main/java/com/example/mody/domain/bodytype/entity/mapping/MemberBodyType.java
  src/main/java/com/example/mody/domain/bodytype/repository/BodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/bodytype/BodyTypeQueryService.java
  src/main/java/com/example/mody/domain/bodytype/service/bodytype/BodyTypeQueryServiceImpl.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandServiceImpl.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryServiceImpl.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/global/common/exception/code/status/BodyTypeErrorStatus.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
  src/main/java/com/example/mody/global/templates/PromptManager.java
Labels: ✨ Feature

#34 ✨ [FEATURE]#19 스타일 추천 API 구현
  src/main/generated/com/example/mody/domain/auth/entity/QRefreshToken.java
  src/main/generated/com/example/mody/domain/backupimage/entity/QBackupFile.java
  src/main/generated/com/example/mody/domain/bodytype/entity/QAnswer.java
  src/main/generated/com/example/mody/domain/bodytype/entity/QBodyType.java
  src/main/generated/com/example/mody/domain/bodytype/entity/QQuestion.java
  src/main/generated/com/example/mody/domain/bodytype/entity/mapping/QMemberAnswer.java
  src/main/generated/com/example/mody/domain/bodytype/entity/mapping/QMemberBodyType.java
  src/main/generated/com/example/mody/domain/member/entity/QMember.java
  src/main/generated/com/example/mody/domain/post/entity/QPost.java
  src/main/generated/com/example/mody/domain/post/entity/QPostImage.java
  src/main/generated/com/example/mody/domain/post/entity/mapping/QMemberPostLike.java
  src/main/generated/com/example/mody/domain/style/entity/QStyle.java
  src/main/generated/com/example/mody/domain/style/entity/QStyleImage.java
  src/main/generated/com/example/mody/domain/style/entity/category/QAppealCategory.java
  src/main/generated/com/example/mody/domain/style/entity/category/QStyleCategory.java
  src/main/generated/com/example/mody/domain/test/entity/QTest.java
  src/main/generated/com/example/mody/global/common/base/QBaseEntity.java
  src/main/java/com/example/mody/domain/auth/jwt/JwtLoginFilter.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/request/StyleRecommendRequest.java
  src/main/java/com/example/mody/domain/style/dto/response/CategoryResponse.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
  src/main/java/com/example/mody/domain/style/entity/StyleImage.java
  src/main/java/com/example/mody/domain/style/entity/category/AppealCategory.java
  src/main/java/com/example/mody/domain/style/entity/category/StyleCategory.java
  src/main/java/com/example/mody/domain/style/repository/AppealCategoryRepository.java
  src/main/java/com/example/mody/domain/style/repository/StyleCategoryRepository.java
  src/main/java/com/example/mody/domain/style/repository/StyleRepository.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryService.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
  src/main/java/com/example/mody/global/templates/PromptManager.java
Labels: ✨ Feature

#38 ✨ [FEATURE]#26 게시글 조회 관련 API 작성
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/dto/response/PostImageResponse.java
  src/main/java/com/example/mody/domain/post/dto/response/PostListResponse.java
  src/main/java/com/example/mody/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/mody/domain/post/dto/response/recode/LikedPostsResponse.java
  src/main/java/com/example/mody/domain/post/entity/PostImage.java
  src/main/java/com/example/mody/domain/post/repository/MemberPostLikeRepository.java
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepository.java
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/mody/domain/post/repository/PostRepository.java
  src/main/java/com/example/mody/domain/post/service/PostQueryService.java
  src/main/java/com/example/mody/domain/post/service/PostQueryServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/code/status/GlobalErrorStatus.java
  src/main/java/com/example/mody/global/common/exception/code/status/MemberPostLikeErrorStatus.java
  src/main/java/com/example/mody/global/config/QueryDSLConfig.java
  src/main/java/com/example/mody/global/dto/response/CursorPagination.java
Labels: ✨ Feature, 🔨 Refactor

#36 ✨ [FEATURE] #18 게시글 삭제 구현
  src/main/java/com/example/mody/domain/backupimage/repository/BackupFileRepository.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/repository/PostImageRepository.java
  src/main/java/com/example/mody/domain/post/service/PostCommandService.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/global/common/base/BaseResponse.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: ✨ Feature

#43 🔨 [FIX] #42-Import문 추가
  src/main/java/com/example/mody/domain/post/controller/PostController.java
Labels: 🐞 Bug

#44 ✨[FEATURE] #39 스타일 추천 결과 저장
  src/main/generated/com/example/mody/domain/style/entity/QStyleImage.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/BodyTypeDTO.java
  src/main/java/com/example/mody/domain/style/dto/request/StyleRecommendRequest.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
  src/main/java/com/example/mody/domain/style/entity/StyleImage.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/annotation/IsEmptyList.java
  src/main/java/com/example/mody/global/common/exception/validator/NotEmptyListValidator.java
Labels: ✨ Feature

#41 ✨ [FEATURE] #40 백업 이미지 등록 API 구현
  src/main/java/com/example/mody/domain/backupimage/service/BackupFileService.java
  src/main/java/com/example/mody/domain/file/controller/FileController.java
  src/main/java/com/example/mody/domain/file/dto/request/BackUpFileRequests.java
  src/main/java/com/example/mody/domain/file/dto/request/BackupFileRequest.java
  src/main/java/com/example/mody/domain/file/dto/request/FileCreateResponse.java
  src/main/java/com/example/mody/domain/file/entity/BackupFile.java
  src/main/java/com/example/mody/domain/file/repository/BackupFileRepository.java
  src/main/java/com/example/mody/domain/file/service/FileService.java
  src/main/java/com/example/mody/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/global/util/S3FileComponent.java
Labels: ✨ Feature, 🔨 Refactor

#46 ✨ [FEATURE] #37 게시글 신고 구현
  src/main/java/com/example/mody/domain/member/converter/MemberConverter.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/entity/mapping/PostReport.java
  src/main/java/com/example/mody/domain/post/repository/PostReportRepository.java
  src/main/java/com/example/mody/domain/post/repository/PostRepository.java
  src/main/java/com/example/mody/domain/post/service/PostCommandService.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/code/status/PostErrorStatus.java
Labels: ✨ Feature

#49 🔨 [REFACTOR] #47 - 체형 분석 API 수정
  src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeController.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandServiceImpl.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryServiceImpl.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#53 Feature/#51 내스타일게시글추천api
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/auth/controller/OAuth2Controller.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/mody/domain/post/service/PostCommandService.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/exception/StyleException.java
  src/main/java/com/example/mody/domain/style/repository/StyleRepository.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryService.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/code/status/StyleErrorStatus.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: ✨ Feature

#63 🔧 [CHORE] #29-SSL 설정
  docker-compose-dev.yml
Labels: 🌏Deploy

#61 🔨 #57 [REFACTOR] - 내 스타일 추천 결과 조회 기능
  src/main/generated/com/example/mody/domain/file/entity/QBackupFile.java
  src/main/generated/com/example/mody/domain/member/entity/QMember.java
  src/main/generated/com/example/mody/domain/post/entity/mapping/QPostReport.java
  src/main/generated/com/example/mody/domain/style/entity/QStyle.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
  src/main/java/com/example/mody/domain/style/entity/StyleImage.java
  src/main/java/com/example/mody/domain/style/repository/StyleRepository.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
  src/main/java/com/example/mody/global/templates/PromptManager.java
Labels: 🔨 Refactor

#54 🔨 [REFACTOR] #52 -백업 이미지 등록 관련 리팩토링
  src/main/java/com/example/mody/domain/file/dto/request/BackUpFileRequests.java
  src/main/java/com/example/mody/domain/file/service/FileService.java
  src/main/java/com/example/mody/domain/post/constant/PostConstant.java
  src/main/java/com/example/mody/domain/post/dto/request/PostCreateRequest.java
Labels: 🔨 Refactor

#56 🔨 [REFACTOR] #45-회원가입 추가 정보 입력 통합
  src/main/generated/com/example/mody/domain/backupimage/entity/QBackupFile.java
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/auth/dto/request/MemberJoinRequest.java
  src/main/java/com/example/mody/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/example/mody/domain/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/mody/domain/auth/jwt/JwtLoginFilter.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandService.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/member/converter/MemberConverter.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandService.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#76 ✨ [FEATURE] #75 - 유저 프로필 조회 API 구현
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/member/controller/MemberController.java
  src/main/java/com/example/mody/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/member/service/MemberQueryService.java
  src/main/java/com/example/mody/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
Labels: ✨ Feature

#67 ✨ [FEATURE] #64- 로거 추가
  .gitignore
  src/main/java/com/example/mody/global/common/exception/ErrorSender.java
  src/main/java/com/example/mody/global/common/exception/ExceptionAdvice.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring-mody.xml
Labels: ✨ Feature

#73 🔨 [Hotfix] #72 - 게시글 삭제 문제 해결
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
Labels: 🐞 Bug

#74 📃[Docs] #66 - 예외 추가 및 정리
  src/main/generated/com/example/mody/domain/member/entity/QMember.java
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/auth/dto/request/MemberJoinRequest.java
  src/main/java/com/example/mody/domain/auth/jwt/JwtLoginFilter.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandService.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
  src/main/java/com/example/mody/global/common/exception/code/status/StyleErrorStatus.java
Labels: 📃 Docs

#71 📝 [Docs] #69 - Post API 예외 정리 및 URL 수정
  src/main/java/com/example/mody/domain/post/controller/PostController.java
Labels: 📃 Docs, 🔨 Refactor

#81 🔨 [Hotfix] #80 - 좋아요 누른 게시글 조회 오류 수정
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/mody/domain/post/service/PostQueryServiceImpl.java
Labels: 🐞 Bug

#83 🔨 [HOTFIX] #82 에러 로그 메세지 추출 시 발생하던 문제 해결
  src/main/java/com/example/mody/global/common/exception/ErrorSender.java
Labels: 🐞 Bug

#86 ✨ [FEATURE] #85 - 프로필 사진 업로드, 이미지 삭제 구현
  src/main/java/com/example/mody/domain/auth/dto/request/MemberRegistrationRequest.java
  src/main/java/com/example/mody/domain/image/controller/S3Controller.java
  src/main/java/com/example/mody/domain/image/dto/request/PostPresignedUrlRequest.java
  src/main/java/com/example/mody/domain/image/dto/request/ProfilePresignedUrlRequest.java
  src/main/java/com/example/mody/domain/image/service/S3Service.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
Labels: ✨ Feature

#89 ✨ [FEATURE] #88 - 스타일 추천 좋아요 기능 추가, 목록 조회 수정
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java
  src/main/java/com/example/mody/domain/post/entity/mapping/PostReport.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponses.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendation.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
  src/main/java/com/example/mody/domain/style/entity/mapping/MemberStyleLike.java
  src/main/java/com/example/mody/domain/style/repository/MemberStyleLikeRepository.java
  src/main/java/com/example/mody/domain/style/repository/StyleCustomRepository.java
  src/main/java/com/example/mody/domain/style/repository/StyleCustomRepositoryImpl.java
  src/main/java/com/example/mody/domain/style/repository/StyleRepository.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryService.java
  src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
Labels: ✨ Feature
