Repository TeamMody/mody-server, pull requests merged in 2025-02, with the labels that each got.

#93 🔨 [HOTFIX] #92 Style 최초 생성 시 likeCount가 null로 출력되던 문제 수정
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
Labels: 🐞 Bug

#99 ✨ [Feature] #84-reissue 수정
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/auth/dto/response/AccessTokenResponse.java
  src/main/java/com/example/mody/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandService.java
  src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/mody/global/config/SecurityConfig.java
Labels: ✨ Feature

#101 ✨ [#100] feature(Member): 회원탈퇴 기능
  src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/mody/domain/member/controller/MemberController.java
  src/main/java/com/example/mody/domain/member/entity/Member.java
  src/main/java/com/example/mody/domain/member/repository/MemberRepository.java
  src/main/java/com/example/mody/domain/member/scheduler/MemberPurgeScheduler.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandService.java
  src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java
Labels: ✨ Feature

#98 🔨 [HOTFIX] #97 게시글 목록 조회 시 정렬 로직 수정
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
Labels: 🐞 Bug, 🔨 Refactor

#103 🔨 [HOTFIX] #102 - 체형 분석 결과 조회 수정
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryServiceImpl.java
Labels: 🐞 Bug, 🔨 Refactor

#108 ✨ [FEATURE] #105 - 핀터레스트 이미지 구현
  build.gradle
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/recommendation/dto/response/analysis/ItemAnalysisResponse.java
  src/main/java/com/example/mody/domain/recommendation/dto/response/analysis/StyleAnalysisResponse.java
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
  src/main/java/com/example/mody/global/common/exception/code/status/CrawlerErrorStatus.java
Labels: ✨ Feature

#110 🔨 [HOTFIX] #109 - 크롬 드라이버 실행 오류 해결
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
Labels: 🐞 Bug, 🔨 Refactor

#113 🚨 [HOTFIX] #111- 리프레쉬 토큰 저장
  src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/mody/domain/style/controller/StyleController.java
  src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
  src/main/java/com/example/mody/domain/style/entity/Style.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
  src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
Labels: 🐞 Bug

#112 🔨 [HOTFIX] #109 - Selenium 버전 변경
  build.gradle
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
Labels: 🐞 Bug, 🔨 Refactor

#115 ♻️ [Refactor] #109 - ChromeDriver 옵션 리팩토링
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
Labels: 🔨 Refactor

#116 Refactor/#114 reissue 오류 수정
  src/main/java/com/example/mody/domain/auth/controller/AuthController.java
  src/main/java/com/example/mody/domain/recommendation/controller/RecommendationControllerInterface.java
  src/main/java/com/example/mody/global/common/exception/code/status/AuthErrorStatus.java
Labels: 🔨 Refactor

#120 ♻️ [Refactor] #109 - ChromeDriver 옵션 수정
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
Labels: 🔨 Refactor

#123 ✨ [#121] feature: 게시물 공개범위 수정 api
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/service/PostCommandService.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
Labels: ✨ Feature

#125 [HOTFIX] #124 - 게시글 조회 api 조인 수정
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
Labels: 🐞 Bug

#130 ✨ [FEATURE] #129 - 게시물 목록 조회 시 필드 추가
  src/main/java/com/example/mody/domain/post/dto/response/PostImageResponse.java
  src/main/java/com/example/mody/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/entity/PostImage.java
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/mody/domain/post/service/PostQueryServiceImpl.java
Labels: ✨ Feature

#134 ♻️ [REFACTOR] #131 - 게시글 조회 API 리팩토링
  src/main/java/com/example/mody/domain/bodytype/entity/BodyType.java
  src/main/java/com/example/mody/domain/post/controller/PostController.java
  src/main/java/com/example/mody/domain/post/dto/response/PostResponses.java
  src/main/java/com/example/mody/domain/post/entity/Post.java
  src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepository.java
  src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/mody/domain/post/service/PostQueryService.java
  src/main/java/com/example/mody/domain/post/service/PostQueryServiceImpl.java
Labels: 🔨 Refactor

#136 ♻️ [REFACTOR] #131 - 담당 API 리팩토링
  src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeController.java
  src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeControllerInterface.java
  src/main/java/com/example/mody/domain/bodytype/dto/request/BodyTypeAnalysisRequest.java
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/bodytype/BodyTypeQueryServiceImpl.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandServiceImpl.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryService.java
  src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryServiceImpl.java
  src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/example/mody/domain/image/controller/S3Controller.java
  src/main/java/com/example/mody/domain/image/controller/S3ControllerInterface.java
  src/main/java/com/example/mody/domain/image/dto/request/PostPresignedUrlRequest.java
  src/main/java/com/example/mody/domain/image/dto/request/ProfilePresignedUrlRequest.java
  src/main/java/com/example/mody/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/example/mody/domain/image/dto/response/S3UrlResponse.java
  src/main/java/com/example/mody/domain/image/service/S3Service.java
  src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
Labels: ✨ Feature

#142 🚨 [HOTFIX] #141 - 최근 바디타입을 가져오던 메서드에 누락된 내림차순 조건 추가
  src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
  src/main/java/com/example/mody/domain/bodytype/service/BodyTypeService.java
Labels: 🐞 Bug

#144 🚨 [HOTFIX] #143 - 로그인 완료 메서드 수정
  src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
Labels: 🐞 Bug
